### ISSUE TITLE
Add RSA 2022 digital video?

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/research-teaching-companion#10]
For the RSA 2022 digital conference, we gave a xoom workshop about teaching with the DCE and/or M&K methods. This included: Pamela Smith, Naomi Rosenkranz, Sofia Gans, Tianna Uchacz, Tillmann Taape, Clement Godbarge.

We have permission from the RSA to share. Do we want in the RTC?

If it is to be added to the RSA, we would need:
- permission from participants
- captioning
- add to M&K's vimeo
- add description

**Comment by ps2270** [comment]
Asked Tillmann and Clement if they could re-record as stand-alone content for the Digital Making and Knowing Page.

**Comment by ps2270** [comment]
#42 Adding to Digital Making and Knowing Page issue. closing this one.
