### ISSUE TITLE
Menu structure - Change "Credits" 

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#100]
"Credits" will appear on About page. Change the menu tab "Credits" on the top-level menu to M&K Hub or M&K Ecosystem or M&K Teaching & Learning 
Decide on this!

**Comment by ps2270** [comment]
I've rethought this. Instead of the previous plan, I think "Credits" should stay as is, and include Credits and Sponsors.
the "About" menu item should be changed to "About M&K" and contain the content that it has now (except for credits and sponsors).
What do you think @njr2128 and @tcatapano?

**Comment by njr2128** [comment]
I believe PHS and I resolved. Closing
