### ISSUE TITLE
Buttons are in a different order on Home Page and Resources page

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#104]
#22 
Please duplicate button order of the Home Page on Both pages.
![Screenshot 2024-04-29 at 15-56-21 Research and Teaching Companion](https://github.com/cu-mkp/research-teaching-companion/assets/25156192/12911f4c-b0c6-4b79-a482-24ddbeb61213)
![Screenshot 2024-04-29 at 15-55-52 Resources Research and Teaching Companion](https://github.com/cu-mkp/research-teaching-companion/assets/25156192/def53a12-2dda-4249-b5b7-3a8976d86997)

**Comment by njr2128** [comment]
done
