### ISSUE TITLE
sp19 Student Projects - migrate from Sandbox

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#110]
@njr2128 
Can you please migrate the sp19  ENGL84031 / HISTGU4031 / COMS4495: Transforming Texts Student Projects from Sandbox to the RTC. 

All parts of these projects are in this folder in GD: https://drive.google.com/drive/folders/1RREgaCPyiZObRRUqPfczSWXeUmLrki_6
I'm not advocating that we link them all, but some would be good. We can discuss.

**Comment by njr2128** [comment]
bring them all over
