### ISSUE TITLE
Failed to deploy

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#114]
@tcatapano @njr2128 
#37 
My extensive additions to the Lesson Plans page did not deploy. 
How to fix this?

**Comment by tcatapano** [comment]
deployment reported error: `Error: error building site: process: readAndProcessContent: "/home/runner/work/research-teaching-companion/research-teaching-companion/content/resources/activity-sheets/_index.md:40:74": unterminated quoted string in shortcode parameter-argument: '/resources/student-projects
'` fixed and re-ran.

**Comment by tcatapano** [comment]
fixed. closing
