### ISSUE TITLE
Field Notes resource

### ISSUE THREAD

**Issue by caro27** [cu-mkp/research-teaching-companion#115]
introduction to field notes and writing them resource. ready for review by @njr2128.

**Comment by caro27** [comment]
Field note doc can be found here: https://docs.google.com/document/d/1w-81z-Me0oNdIbvTT7EhMseQyecEYZblmiBXgniHjFI/edit

**Comment by njr2128** [comment]
@ps2270 and @caro27 - I've reviewed Caroline's doc (IT IS FANTASTIC!!) and made minor edits, and have now created the markdown file. Please review it: https://github.com/cu-mkp/research-teaching-companion/blob/main/content/resources/activity-sheets/introduction-fieldnotes.md

I will also link in the RTC in the appropriate places

**Comment by njr2128** [comment]
I just did a new build so you can view it in the site too: https://teaching640.makingandknowing.org/resources/activity-sheets/introduction-fieldnotes/

**Comment by ps2270** [comment]
@caro27
I agree it's fantastic.

**Comment by caro27** [comment]
Thank you! Let me know if you'd like any changes.

**Comment by ps2270** [comment]
This is up on the site now. closing.
