### ISSUE TITLE
broken links by file

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/research-teaching-companion#116]
as of last build:

`content/introduction.md`:
- Broken link to "syllabus"
- Broken link to "activitysheet"
- Broken link to "project"
- Broken link to "casestudy"

`content/resources/activity-sheets/activitysheet_inks.md`:
- Broken link to "/documents/activity-sheets/presentation_iron-gall-inks-2023.pdf"
- Broken link to "/documents/activity-sheets/uchacz_2023_materialiality-of-text.docx"
- Broken link to "/documents/activity-sheets/uchacz_2023_materialiality-of-text.pdf"

`content/resources/activity-sheets/activitysheet_dyeing.md`:
- Broken link to "../casestudies"
- Broken link to "/documents/activity-sheets/2023_dyes_cochineal-history-chem-prep.pdf"
- Broken link to "/documents/activity-sheets/rosenkranz_2018_dyes_cochineal-step-by-step.pdf"
- Broken link to "/documents/activity-sheets/2023_dyes-pigments_samples.pdf"
- Broken link to "/documents/activity-sheets/activitysheet_dye-material-sourcing.docx"
- Broken link to "/documents/activity-sheets/activitysheet_dye-material-sourcing.pdf"
- Broken link to "/documents/activity-sheets/activitysheet_dye-kitchen-dyeing.docx"
- Broken link to "/documents/activity-sheets/activitysheet_dye-kitchen-dyeing.pdf"
- Broken link to "/documents/activity-sheets/activitysheet_mordants-dyes-recipes-calculator.docx"
- Broken link to "/documents/activity-sheets/activitysheet_mordants-dyes-recipes-calculator.pdf"
- Broken link to "/documents/activity-sheets/activitysheet_mordants-dyes-recipes-automatic-calculator.xlsx"
- Broken link to "dyes-cochineal_assignment_downloadable_2023.pdf"
- Broken link to "/documents/activity-sheets/sp23_handout_dyeing-textiles_general-process.pdf"
- Broken link to "/documents/activity-sheets/sp23_printout_recipe-example-piemontese.pdf"

`content/resources/activity-sheets/activitysheet_lake-pigments.md`:
- Broken link to "/documents/activity-sheets/pigment-cochineal-lake_assignment"
- Broken link to "/documents/activity-sheets/pigment-madder-lake_assignment"
- Broken link to "/documents/activity-sheets/sp22_fld_rosenkranz_naomi_madder-lake-trio"
- Broken link to "/documents/activity-sheets/presentation_sp23_rosenkranz_naomi_lakes_cochineal-history-chem-prep"
- Broken link to "/documents/activity-sheets/presentation_sp23_rosenkranz_naomi_lakes_madder-history-chem-prep"
- Broken link to "/documents/activity-sheets/uchacz_2024_lab1_reflection-assignment-background.docx"
- Broken link to "/documents/activity-sheets/uchacz_2024_lab1_reflection-assignment-background.pdf"
- Broken link to "/documents/activity-sheets/uchacz_2024_lab1_reflection-assignment.docx"
- Broken link to "/documents/activity-sheets/uchacz_2024_lab1_reflection-assignment.pdf"
- Broken link to "/documents/activity-sheets/lakes-in-Fr-640_2021.pdf"
- Broken link to "/documents/activity-sheets/lakes-trade-labor-in-Fr640.pdf"

`content/resources/activity-sheets/activitysheet_stucco.md`:
- Broken link to "/documents/activity-sheets/stucco_assignment_downloadable_2021.pdf"
- Broken link to "/documents/activity-sheets/uchacz_2024_stucco_reflection-assignment.docx"
- Broken link to "/documents/activity-sheets/uchacz_2024_stucco_reflection-assignment.pdf"

`content/resources/activity-sheets/activitysheet_paintingpigments.md`:
- Broken link to "/documents/activity-sheets/painting_assignment_downloadable_2021.pdf"
- Broken link to "/documents/activity-sheets/uchacz_2024_lab2_reflection-assignment.docx"
- Broken link to "/documents/activity-sheets/uchacz_2024_lab2_reflection-assignment.pdf"

`content/resources/activity-sheets/activitysheet_varnishes.md`:
- Broken link to "/documents/activity-sheets/activitysheet_varnishes-protocol-slsv.docx"
- Broken link to "/documents/activity-sheets/activitysheet_varnishes-protocol-slsv.pdf"
- Broken link to "/documents/activity-sheets/activitysheet_varnishes-protocol-ttv.docx"
- Broken link to "/documents/activity-sheets/activitysheet_varnishes-protocol-ttv.pdf"
- Broken link to "/documents/activity-sheets/material-sourcing-varnishes-resins.docx"
- Broken link to "/documents/activity-sheets/material-sourcing-varnishes-resins.pdf"
- Broken link to "/documents/activity-sheets/glossary-turpentine-resins-balsams.pdf"

`content/resources/activity-sheets/breadmolding_resources-for-the-instructor.md`:
- Broken link to "/documents/activity-sheets/breadmolding-student-activity-sheet"

`content/resources/case-studies.md`:
- Broken link to "/documents/case-studies/sp23_uchacz_tianna_syllabus-viza-689_art-craft.pdf"
- Broken link to "/documents/activity-sheets/verdigris_assignment_downloadable_2021.pdf"
- Broken link to "/documents/case-studies/sp24_uchacz_tianna_canvas-lab2-arts-150_global-art-history-survey.pdf"
- Broken link to "/images/sp24_uchacz_tianna_egg-media-arts-150_global-art-history-survey.png"
- Broken link to "/images/sp24_uchacz_tianna_oil-media-arts-150_global-art-history-survey.png"
- Broken link to "images/sp24_uchacz_tianna_paint-grid-arts-150_global-art-history-survey.png"
- Broken link to "/documents/activity-sheets/2023_dyes_cochineal-history-chem-prep_TAMU-compressed.pdf"
- Broken link to "/documents/activity-sheets/sp23_printout_samples-amounts.pdf"
- Broken link to "/documents/activity-sheets/sp23_handout_dyeing-textiles_general-process.pdf"
- Broken link to "/documents/activity-sheets/sp23_poster_bioart.pdf"
- Broken link to "/documents/activity-sheets/rosenkranz_2018_dyes_cochineal-workshop_overview-of-dye-chemistry-history.pdf"
- Broken link to "/documents/activity-sheets/rosenkranz_2018_dyes_cochineal-step-by-step.pdf"
- Broken link to "/documents/activity-sheets/rosenkranz_2018_dyes_handout_dyeing-with-cochineal.pdf"
- Broken link to "/documents/activity-sheets/su22_fld_cunningham_annika_onion-skin-dyeing-template+notes.xlsx"
- Broken link to "/documents/activity-sheets/su22_fld_cunningham_annika_onion-skin-dyeing-template+notes.pdf"
- Broken link to "/documents/activity-sheets/su22_fld_cunningham_annika_onion-skin-dyeing-template+notes-2-greens.xlsx"
- Broken link to "/documents/activity-sheets/su22_fld_cunningham_annika_onion-skin-dyeing-template+notes-2-greens.pdf"

`content/resources/student-projects/_index.md`:
- Broken link to "materials"

`content/resources/student-projects/fa21_jacobson_beah_final-project-know.md`:
- Broken link to "/documents/student-projects/fa21_jacobson_beah_final-project-know_tl_know.pdf"

`content/resources/student-projects/fa21_ghoneima_hana_final-project-oral-culture.md`:
- Broken link to "/documents/student-projects/fa21_ghoneima_hana_final-project_tl_said.pdf"
- Broken link to "/documents/student-projects/fa21_ghoneima_hana_final-project_tl_pro.pdf"
- Broken link to "/documents/student-projects/fa21_ghoneima_hana_final-project_tl_pl.pdf"

`content/resources/student-projects/su22_fld_cunningham_annika_onion-skin-dyeing.md`:
- Broken link to "/documents/student-projects/su22_fld_cunningham_annika_onion-skin-dyeing-template+notes.pdf"
- Broken link to "/documents/student-projects/su22_fld_cunningham_annika_onion-skin-dyeing-template+notes-2-greens.pdf"

**Comment by tcatapano** [comment]
For these broken links:

* check that intermediate directory is correct
* file extension is correct

Im also beginning to think that with the ref shortcodes, file extensions are ignored and may cause trouble when there are two files with the same name at the target directory. Just a theory...

**Comment by njr2128** [comment]
superseded by #135 and #134
