### ISSUE TITLE
Credits for RTC

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#123]
Need to revise the Credits webpage for RTC-specific questions.
Include a link to DCE credits.

**Comment by njr2128** [comment]
student credits have been added. source tables are in the GD: https://docs.google.com/spreadsheets/d/15B7pqWXVOc6qb_VRhjBRJTEhkO98xEYAayDZDpo8U1M/edit?gid=1695193176#gid=1695193176

**Comment by ps2270** [comment]
Add a section on something like
"Planning and Implementation Team" =
NJR, PHS, THC, THU, SJP, TT
Planning in 2018-21 and 2024 Worksprint

**Comment by ps2270** [comment]
I have added "Planning and Implementation" Team - see what you think, @njr2128 and @thuchacz

**Comment by thuchacz** [comment]
I think it looks pretty good, Pamela. I like the idea of "Planning and Implementation." A few thoughts:

1. The second paragraph in the credits intro (i.e., the bit just below the first picture on the page) takes for granted that readers will know what "the edition of Ms. Fr. 640" and "the edition" more broadly. It might be clearer if in the first paragraph  of this intro (i.e., the one before the picture), you use the term "digital critical edition" or "edition" to describe _Secrets of Craft and Nature_.
2. It's a bit confusing to have credits for the "Project Team and Staff" for the edition to come before the credits for the companion. I get that the edition is the basis for the companion, but I would move this (and the opening statement that not everyone listed below worked directly on the RTC) below the RTC work sprint section.

**Comment by ps2270** [comment]
Revised Credits in accord with Tianna's suggestions.
@njr2128  See if it's ok and then close

**Comment by ps2270** [comment]
I've completed the Credits page.
@njr2128 can you please sign off and close this issue?

**Comment by njr2128** [comment]
Terry and I reviewed and looks good to us! We corrected a few typos and styling, including table rendering (related to #57)
