### ISSUE TITLE
Syllabi - rename and reupload all pre-2021 syllabi

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#124]
#51 
All pre-2021 syllabi must be renamed to the following protocol:
syllabus_[date]]_[brief title which can include course number and short name of course].[file extension]
e.g.,
syllabus_fa14_gr8906-craft-and-science.pdf

When a pdf and docx have been downloaded and renamed, they need to be re-uploaded to static docs: https://github.com/cu-mkp/research-teaching-companion/tree/main/static/documents

**Comment by njr2128** [comment]
@ps2270 - they have all been renamed as per the protocol:
`syllabus_fa18_gr8906-craft-and-science` but for each semester+year combo

**Comment by ps2270** [comment]
@njr2128 
fa15 is missing from the static docx folder

**Comment by ps2270** [comment]
PHS added fa15 and is closing this issue
