### ISSUE TITLE
/img directory not resolving in built site

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/research-teaching-companion#127]
the `img` dir inside of the theme's `/static/` dir is not appearing in the built site (i.e., what is in `public` after running the `hugo` command), because the url is `https://teaching640.makingandknowing.org//img/mk-banner-logo.png`.  I suspect this is related to the baseURL definition in config.toml which includes a trailing slash ` https://teaching640.makingandknowing.org/` because the site generated with the `hugo server` command does work, presumably because it is not using the baseURL so there is no double slash.

**Comment by ps2270** [comment]
The built site is actually mostly there this morning, but none of the md links work now - only the html links work!! Akkk.

**Comment by ps2270** [comment]
Also, the logo is not displaying, as you probably know.

**Comment by njr2128** [comment]
> The built site is actually mostly there this morning, but none of the md links work now - only the html links work!! The non-working md. links send you back to the Resources landing page. Akkk!

@ps2270 - Can you give us some examples? Which links?

**Comment by njr2128** [comment]
> Also, the logo is not displaying, as you probably know.

Yes, that is what led us to this issue! Neither the RTC logo nor the ones in the footer for CSS or CU. Terry is troubleshooting - it seems to be a Hugo build issue

**Comment by njr2128** [comment]
Rebuild of site does not seem to have resolved the change to "text-bg.png" -- need to test with something easier to diagnose, eg banner logo or footers.

Also, use:
`aws s3 sync ./public/ s3://teaching640-dev/ --delete`

**Comment by njr2128** [comment]
Removing `{{ .Site.BaseURL }}` seems to fix the problem! The new build after the latest commit (https://github.com/cu-mkp/research-teaching-companion/commit/a7159712c37f662279734db05d96a72203935eb8) has the CU logo
![image](https://github.com/user-attachments/assets/1faa544a-2b26-44bf-9b39-2bdb60610cf4)

**Comment by njr2128** [comment]
Logos are fixed!
![image](https://github.com/user-attachments/assets/ab15a786-5847-4897-a126-2342d045a236)

**Comment by njr2128** [comment]
The one remaining item is the background of the header bars on each page:
![image](https://github.com/user-attachments/assets/1b46a450-c09c-4792-8769-67c3c8f1cd70)

Should be like edition640:
![image](https://github.com/user-attachments/assets/1fc4e2ec-a82f-4bed-80ac-087291583774)

**Comment by njr2128** [comment]
Found the section on the site where this background header is controlled: 
![image](https://github.com/user-attachments/assets/09cc59c7-171c-4089-a129-a4b03ae7181b)
 It likely needs an absolute link bc it is anchored just to the domain (cu-mkp.github.io) and not to the project (https://cu-mkp.github.io/research-teaching-companion)
Going to test if this will work in teaching640.makingandknowing.org before we change the link again

**Comment by njr2128** [comment]
Removing the SiteBaseURL and adding the leading slash to `img/` has resolved the problem in teaching640.makingandknowing.org!
![image](https://github.com/user-attachments/assets/98ae688a-78be-48ed-930a-e79a432641ef)

NOTE: this still means it does not show up in the github.io page bc it does not append it to the right directory of the site -- but this is really not important:
![image](https://github.com/user-attachments/assets/c2dc728b-a5b7-49c5-be42-d8abd7137648)
