### ISSUE TITLE
homepage: move image from above buttons to below

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/research-teaching-companion#138]
PHS now put the image here: 
![image](https://github.com/user-attachments/assets/fabd5173-5c58-4dfc-8b07-92d086e6fb88)

want it here: 
![image](https://github.com/user-attachments/assets/550ebde2-ed62-45f3-8e8c-263982f07fbe)

**Comment by njr2128** [comment]
pages to edit: 
- https://github.com/cu-mkp/research-teaching-companion/blob/main/themes/rtc/layouts/index.html (contains buttons and lower image)
- https://github.com/cu-mkp/research-teaching-companion/blob/main/content/_index.md (contains text and upper image that needs to be moved

**Comment by njr2128** [comment]
@ps2270, I have now moved it below and sized it to the same size as the other image:
![image](https://github.com/user-attachments/assets/434ee4ff-19ec-4e46-9e74-e51e243a4ad2)

They are still not centered, which will require a separate investigation

**Comment by ps2270** [comment]
@Naomi Rosenkranz ***@***.***> Great. How do you size images?  I
don't think it's in the README, and the images on the Introduction page
definitely need it

**Comment by njr2128** [comment]
You must use html syntax instead of markdown:
`<img src="/images/sp22_azurite-session.jpg" alt="Making and Knowing Lab azurite session" width="640" height="360"/>`
You can play around with the width/height as you'd like. 
https://www.w3schools.com/tags/tag_img.asp -- look at the other attributes available for the image tag - might be able to use the alignment attribute to center?

**Comment by ps2270** [comment]
I found the size width=740, height=460 is a good size for the pages.
Also, @njr2128 I think the problem of centering is not acute and doesn't warrant a lot of time spent on it - as you can see from the way it renders on my screen
![Screenshot 2024-08-10 at 07-56-51 Research and Teaching Companion](https://github.com/user-attachments/assets/41b9413c-1b6c-4f89-87d8-80b31b022fe5)
