### ISSUE TITLE
Final projects Assignment Sheet

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#141]
Can we produce a non-GD version of the Final Projects Assignment Sheet for 4962: https://docs.google.com/document/d/1XG-QNmZfSSBAMmFqyBZLAm9nosg7VvF78a8MnMAD_Y8/edit#heading=h.ez44uvfi7doo
It contains valuable resources and links, but is full of M&K GD files and folders

**Comment by caro27** [comment]
Static version created and uploaded as both pdf and docx. 
Forgive me for my lack of knowledge, but I wasn't quite sure what to do about links in the doc to other RTC pages (for example, lesson plans). I've left them for now, but can remove them if that is the right call and upload again. 
have updated any dead links in the RTC and shared student version.

**Comment by ps2270** [comment]
@caro27 
Thank you!
I'd like to make a few revisions, so can you tell me where the original of these documents lives? Do you have it in google drive somewhere?
I can download the docx, but if it's in a GD, so much easier for both of us to work on it if necessary.

**Comment by caro27** [comment]
https://docs.google.com/document/d/12_dKLGGG3-k-Ez33O_HtYZHeBafqg4kMeEM4fyuFw7k/edit#heading=h.dg04h1g0ncqh
@ps2270

**Comment by ps2270** [comment]
Thanks @caro27 
I'm done making changes - can you review and accept or not all my tracked changes - we just leave the links to RTC in it, except where I've deleted them. I'll provide some language about how this is an example Final Project example
BTW, this is NOT the one we'll use for our syllabus, which needs to contain all that language and links that have been deleted here.

**Comment by caro27** [comment]
Done! Thanks

**Comment by ps2270** [comment]
Linked in the Lesson-Plans for Hands-On page - under Tips for Hands-On.
closing now
