### ISSUE TITLE
2021-2023-GU4962 Syllabi and Digital-course-syllabi conversion 

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#142]
@njr2128 or @caro27  please link the RTC webpage "student projects" on each syllabus, convert the syllabi from google doc to docx, and upload to static. @ps2270 will link them.
Moving this issue from closed #51

**Comment by njr2128** [comment]
I have updated all syllabi and linked both pdf and docx versions for all semesters

**Comment by ps2270** [comment]
@njr2128 
Can you please clarify what you mean by "linked" pdf and docx versions for all semesters - the syllabi are still showing up as google doc published.

**Comment by ps2270** [comment]
@njr2128 - Oh, never mind - now I see the problem. You updated on the Syllabi page and I am working on the Student Projects page. I will update Student Projects page.

**Comment by ps2270** [comment]
#44 
Updated on Student Projects page.
Closing again.
