### ISSUE TITLE
reroute RTC site from github.io to teaching640

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/research-teaching-companion#15]
Through cloudfront?

https://cu-mkp.github.io/research-teaching-companion/

https://teaching640.makingandknowing.org/

**Comment by njr2128** [comment]
WAIT until we are ready to release the first public release of the site.
Use the github.io site as "dev" or "staging"

**Comment by njr2128** [comment]
We have set up a CloudFront distribution, but have encountered errors with accessing site pages from the landing page. This seems to be due to Hugo's index.html needs that are different from AWS

**Comment by njr2128** [comment]
Another issue just encountered - permissions:
![image](https://github.com/cu-mkp/research-teaching-companion/assets/14779727/b7221fd1-6dd4-461c-ac49-32ba82eec9d8)

**Comment by tcatapano** [comment]
Working now. The function is actually: 

```
def lambda_handler(event, context):
    request = event['Records'][0]['cf']['request']
    uri = request['uri']
    
    # If URL ends with a slash, append index.html
    if uri.endswith('/'):
        request['uri'] += 'index.html'
    
    return request
```

The problem seemed to be related to the setting of 'Behaviors" in CloudFront:

Path Pattern is `* `
Lambda Function Association is `Viewer Request`

**Comment by ps2270** [comment]
Accomplished. closing
