### ISSUE TITLE
Lake-making resources - correct and add

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#154]
@njr2128
See https://teaching640.makingandknowing.org/resources/activity-sheets/sp22_fld_rosenkranz_naomi_madder-lake-trio/
There is intro material at the top of the page that needs completing!

![Screenshot 2024-09-12 at 23-16-45 Research and Teaching Companion](https://github.com/user-attachments/assets/abf226b0-1003-4264-9fa3-c686d72cf13d)

Do you think this ppt is a useful addition to the lake-making page. If so, please add it as a pdf.
https://docs.google.com/presentation/d/1ty7uOlzrtqXS6G4wKvc5si9j6FLZ7-3xRcnMc4dnd_M/edit#slide=id.gdd3af8a445_0_287

**Comment by ps2270** [comment]
This link also throws a 404 error - 
[Presentation: Madder Lake: History, Chemistry, and Preparation](https://teaching640.makingandknowing.org/documents/pdf/presentation_sp23_rosenkranz_naomi_lakes_madder-history-chem-prep.pdf/)
ON MAKING LAKE PIGMENTS PAGE

![Screenshot 2024-09-16 at 16-48-39 research-teaching-companion_static_documents_pdf_presentation_sp23_rosenkranz_naomi_lakes_madder-history-chem-prep pdf at main · cu-mkp_research-teaching-companion](https://github.com/user-attachments/assets/d880378d-c845-4e35-920b-04dc2d32c33b)

**Comment by njr2128** [comment]
This throws an error: https://teaching640.makingandknowing.org/documents/pdf/presentation_sp23_rosenkranz_naomi_lakes_madder-history-chem-prep.pdf/

but this works: https://teaching640.makingandknowing.org/documents/pdf/presentation_sp23_rosenkranz_naomi_lakes_madder-history-chem-prep.pdf

**Comment by tcatapano** [comment]
this makes sense to me. A (non-html) file should be pointed to directly (i.e., without a trailing slash)

**Comment by ps2270** [comment]
deleted the trailing slash on the pdf file, but it still doesn't work.

**Comment by tcatapano** [comment]
This link works for me: https://teaching640.makingandknowing.org/documents/pdf/presentation_sp23_rosenkranz_naomi_lakes_madder-history-chem-prep.pdf

Note that the link under https://teaching640.makingandknowing.org/resources/activity-sheets/activitysheet_lake-pigments/#teaching-lake-pigments still has the trailing slash

**Comment by njr2128** [comment]
I've updated and made a new build 1 min ago. Closing here as I believe all issues are fixed. Links are working for me
