### ISSUE TITLE
aws cli build error

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/research-teaching-companion#155]
On my new Windows 11 laptop running WSL, I get the following error after trying to publish to aws:
```
[njr2128@asus-njr research-teaching-companion](main)$ aws s3 sync ./public/ s3://teaching640-dev/ --delete
fatal error: An error occurred (RequestTimeTooSkewed) when calling the ListObjectsV2 operation: The difference between the request time and the current time is too large
```
This is after running:
1. `rm -rf public/`
2. `hugo`

@tcatapano - help?

**Comment by tcatapano** [comment]
@njr2128 : can you check that your computer's clock is set correctly? Try this:

```
On Windows:

    Go to Control Panel > Clock and Region > Date and Time.
    Under the Internet Time tab, click Change settings, and make sure that Synchronize with an Internet time server is enabled.

```

At the command line the `date` command will tell you what time it thinks it is:

```
$ date
Mon Sep 23 09:03:10 PDT 2024
```

**Comment by njr2128** [comment]
womp! at the command line, it thinks it is Friday.

I do not see any settings for Internet Time in the control panel - I think bc it is Windows 11. Gonna google that now and see what I can find:
![image](https://github.com/user-attachments/assets/eaf93f0b-f821-4753-8f8d-1b103b500fa7)

**Comment by tcatapano** [comment]
from our helpful robots at ChatGpt:
```
sudo service ntp stop  # if ntpd is running
sudo ntpdate -u pool.ntp.org
sudo service ntp start

```

**Comment by njr2128** [comment]
```
[njr2128@asus-njr ~]$ sudo service ntp stop
[sudo] password for njr2128:
ntp: unrecognized service
[njr2128@asus-njr ~]$
```

**Comment by njr2128** [comment]
So I found this in my googling, and saw I had already tried this and it did not make a difference (I even restarted WSL to make sure it went into effect). I wonder if I need to restart my machine completely: https://www.elevenforum.com/t/sync-clock-time-with-internet-time-server-in-windows-11.1320/:
![image](https://github.com/user-attachments/assets/4a408d52-0919-4105-b585-3b8a2da6e4f3)

**Comment by tcatapano** [comment]
@njr2128 When you run `date` at the command line, what time do you get?

**Comment by njr2128** [comment]
Friday still

**Comment by njr2128** [comment]
No trying through control panel (as opposed to settings): 
![image](https://github.com/user-attachments/assets/b1091b34-a6bf-4806-8c51-e36cf67fcdc6)

**Comment by njr2128** [comment]
Tried control panel and I am still stuck in the past (it has now updated to Saturday but only because time has passed and it thinks it is 1:30 am)

**Comment by tcatapano** [comment]
Have you tried restarting the machine?

**Comment by tcatapano** [comment]
> ```
> [njr2128@asus-njr ~]$ sudo service ntp stop
> [sudo] password for njr2128:
> ntp: unrecognized service
> [njr2128@asus-njr ~]$
> ```

ugh. looks like wsl doesnt run its own time service. Relies on windows

**Comment by njr2128** [comment]
restarting has resolved! 
![til](https://media1.tenor.com/m/eqqPlamdM1gAAAAd/hello-it-have-you-tried.gif)
