### ISSUE TITLE
add content from sandbox to rtc

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/research-teaching-companion#20]
move over all 
- student projects
- assignment sheets
- presentations & resources
- collaborator pilot courses
- Assessment and Evaluation Tools

**Comment by njr2128** [comment]
Outstanding: 
- updating "index" pages with links to all the added content (eg, what is currently in https://github.com/cu-mkp/research-teaching-companion/blob/main/content/resources/activity-sheets/_index.md has not been updated with the most up-to-date content, which can be found in https://github.com/cu-mkp/sandbox/blob/main/docs/index-course-projects.md)
- assessment tools

**Comment by ps2270** [comment]
@njr2128 can we close this now?
