### ISSUE TITLE
Lesson Plan - Historical Culinary Recipe Reconstruction

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#27]
[2023 version](https://docs.google.com/document/d/1UvcR_0ClX_7lefNUdWeJ-H1OW7_jvIqwL_wvN8j6vE4/edit)

- Use Template to format
- are links necessary and durable 
- how to deal with the assigning of obscure recipes? Include these as pdfs attached to the Instructor sheet?

**Comment by njr2128** [comment]
closing bc it is duplicated by #82
