### ISSUE TITLE
Lesson Plan - Jaspe Contrefait

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#33]
Imitation jasper with horn
[Jasper](https://drive.google.com/drive/folders/1hJeMDs-Va_uLqQE74Z72dPPoQeOD-A7k?usp=drive_link) - the materials in here should be parsed and decisions made about what and how to include
https://fieldnotes.makingandknowing.org/pre-2018-Fall/sp18_mk_team_varnishes-for-imitation-jasper-reference-copy.html 
https://fieldnotes.makingandknowing.org/pre-2018-Fall/SP18Varnishesforimitationjasper.html

**Comment by ps2270** [comment]
Update as of 4/28/24
Sophie and Tillmann have worked up the Instructor Resources sheet, but got up to metal leaf application
here: https://drive.google.com/drive/folders/1zQd98jsDgMgWxoaQ-uTiNpUFAEHCQ9md?usp=drive_link
PHS and NJR will take over.

**Comment by njr2128** [comment]
Ch360 article citation: Naomi Rosenkranz and Pamela H. Smith. “Making and Knowing: Reconstructing an Author-Practitioner’s Epistemic World and Material Imaginary.” In *Cultural Heritage 360, special issue of Endeavour*, edited by Tianna Helena Uchacz, Giles Gasper, and Stephen J.C. Taylor. Under review, expected Spring 2024.

**Comment by njr2128** [comment]
Review and add other resources in the "Jasper" and "Varnishes" Materials folder in the M&K GD

**Comment by ps2270** [comment]
@njr2128 CH360 pdf is more than 25 MB and cannot be uploaded. Not sure what to do?

**Comment by ps2270** [comment]
Status update on Jasper Making page
PHS is finished adding resources and reviewing and revising the page.
To be done:
@thuchacz adding images
@thuchacz adding a section on making the "rose"
@njr2128  Add preprint of CH360 - the file is too big to add to the static documents file - what to do?

**Comment by thuchacz** [comment]
@ps2270 Jasper images and rose section are ready for review.
@njr2128 perhaps reduce the size of the images or simply leave the flickr links?

**Comment by ps2270** [comment]
@thuchacz BEAUTIFULLY DONE!!  The images and rose section made my evening - thank you!!

**Comment by ps2270** [comment]
lesson plan is complete. Closing
