### ISSUE TITLE
Using M&K Resources - Videos

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#46]
Videos by collaborators - QUESTIONS:
Collaborator videos (see below)
From NJR & THC & CMS: Video considerations:
Hosting and streaming (we are using a commercial service - Vimeo - what happens if they go away?)
Proliferate across services: Flickr, Youtube, Vimeo, look into AWS self-streaming options(?)
Think about cost and maintenance of this
Archiving
Eg through Academic Commons (what we have done for the lab tour playlist) - but need CU Libraries
https://academiccommons.columbia.edu/doi/10.7916/d8-8r5c-2564 
Zenodo? Does not have a player but can archive
Formats
Captioning - time-consuming - collaborator videos 
Other ADA compliance and accessibility concerns?
Are there any permissions or consent/contributions considerations?

**Comment by caro27** [comment]
uploaded Christina Neilson and Sofia Gans to Vimeo. Issue of Sofia Gans student privacy remains.

**Comment by ps2270** [comment]
complete except for Vera Keller, which is referenced in #43 . Closing now.
