### ISSUE TITLE
update index pages

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/research-teaching-companion#50]
#20

updating "index" pages with links to all the added content (eg, what is currently in https://github.com/cu-mkp/research-teaching-companion/blob/main/content/resources/activity-sheets/_index.md has not been updated with the most up-to-date content, which can be found in https://github.com/cu-mkp/sandbox/blob/main/docs/index-activity-assignments.md)

**Comment by njr2128** [comment]
Need to update or create each of these index pages

![image](https://github.com/cu-mkp/research-teaching-companion/assets/14779727/68e92d46-5bbc-455c-aa39-fc4e60561e8f)

**Comment by ps2270** [comment]
done. closing
