### ISSUE TITLE
Syllabi - Convert all pre-2021 Syllabi

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#51]
Convert all Syllabi (use only "Web" versions of syllabi) before 2021 to pdf, docx, and potentially markdown or html (NJR and THC will work on this through pandoc)

**Comment by njr2128** [comment]
Also needed for post-2021 syllabi!

**Comment by njr2128** [comment]
I have added a .md version of sp23 as a test. It is the unedited version as spit out by pandoc; the only edit is the filepath name for images.

It is in the index so we can take a look at it "in situ" in the RTC site. We will also need to add links to the pdf and docx to the index

**Comment by caro27** [comment]
- double spacing. for example "instructor to pamela smith line break
- take out emails, office hours, office location. 
- take out extra *

**Comment by caro27** [comment]
CMS has gone through the following web syllabi:
- fall 2014
- spring 2015
- fall 2015
- spring 2016
- fall 2016
- spring 2017
- fall 2017
- fall 2018
- summer 2021
- fall 2021
- spring 2022
- spring 2023

syllabi can be found here: https://www.makingandknowing.org/laboratory-seminars/

Once approved by @ps2270, will downolad as docx and pdf and upload to static.

**Comment by caro27** [comment]
add list of student research essays that resulted from each semester

**Comment by caro27** [comment]
G8906 pdf and docx syllabi are uploaded to static.

**Comment by ps2270** [comment]
@caro27 add anticipatory links to student projects for all 4962 courses, make pdfs and docx for each, and upload to static

**Comment by ps2270** [comment]
sample syntax for links:
 https://teaching640.makingandknowing.org/resources/student-projects/fa21_alberts_naomi_final-project_ph-lesson/

**Comment by ps2270** [comment]
8/6/24: 
Still to be completed on 4962 and digital course syllabi:
download as docx (they are now google web publication), list the student projects that resulted from each semester on the relevant syllabus, using links to teaching640, e.g., 
sample syntax for links:
https://teaching640.makingandknowing.org/resources/student-projects/fa21_alberts_naomi_final-project_ph-lesson/

then upload these syllabi to static, link them on the syllabi index github page.

**Comment by ps2270** [comment]
Change of plans: @njr2128  simply link to student projects RTC page on each syllabus, convert to docx, and upload. @ps2270 will link them

**Comment by ps2270** [comment]
Making a new issue for GU4962, i.e., post-2021 syllabi and closing this one
