### ISSUE TITLE
Naming Protocols for RTC Sections

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#53]
Also to be found [here](https://github.com/cu-mkp/research-teaching-companion/blob/main/how-tos/publishing-to-rtc.md#type-values): 
Making & Knowing Syllabi [naming protocol: **syllabus**]

Using M&K Resources [naming protocol: **casestudy**]

Lesson Plans for Hands-On [**activitysheet**]

Reflections on Hands-On [**reflection**] 

Student Projects [**project**]

Digital Fr. 640 [**digital**]

**Comment by njr2128** [comment]
Decisions from discussion: 
- change " digital fr. 640" --> "digital making and knowing"
- m&k resources in use | m&k use cases

**Comment by ps2270** [comment]
implemented. closing.
