### ISSUE TITLE
Add image to Home page

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#54]
Terry,
Can you add this image to the Home page underneath the buttons - I don't trust my knowledge at this point:
[static/images/Making and Knowing Lab spring 2018.jpg
](https://github.com/cu-mkp/research-teaching-companion/blob/main/static/images/Making%20and%20Knowing%20Lab%20spring%202018.jpg)
This is not a high priority, but I am trying to familiarize myself with functions.
Thank you

**Comment by ps2270** [comment]
need to re-size this image

**Comment by njr2128** [comment]
added 640x360 - chosen arbitrarily as a trial. The result was that the image is smaller, but left-aligned. 
![image](https://github.com/cu-mkp/research-teaching-companion/assets/14779727/8cccf312-0992-4efb-90a0-b7e2b288d55b)

Note also that it does not seem to maintain aspect ratio if you pull up the image on a small screen

![image](https://github.com/cu-mkp/research-teaching-companion/assets/14779727/2f00a566-45a5-45d7-8af8-b344b66f64fb)


To be dealt with later when we work on this page in earnest
