### ISSUE TITLE
change image syntax and paths for all .md files

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/research-teaching-companion#63]
images that are included in any .md page in /content/ are included as if they are in the Sandbox. We need to update the syntax and the filepaths

**Comment by njr2128** [comment]
There are two potential origin syntaxes to look for:
- "html" syntax `<img src="./images/image7.png" alt="A black and white drawing of a person holding a vase" />` (which Terry fixed in [09f5669](https://github.com/cu-mkp/research-teaching-companion/commit/09f5669972103a7a251ff347c87d93d2bf0b70a0)
- "markdown" syntax `![dyes-cochineal_header](../images/cochineal-dyed-textiles-mix.JPG?raw=true)` - although not all have `?raw=true`

**Comment by njr2128** [comment]
Here is another example of "html" syntax to be converted to the new syntax:
- `<img src="./media-jacobson/image4.png" style="width:6.5in;height:4.23611in" alt="Chart" />`
- `<img src="./media-ghoneima/image3.png" style="width:6.09314in;height:3.77in" alt="Chart" />`
- `<img src="./media-gardner/image2.jpg" style="width:2.91721in;height:3.93229in" />`
- 1<img src="./media-christensen/image5.png" style="width:5.88021in;height:4.04867in" />`

**Comment by tcatapano** [comment]
Using the following regexp will change the html based img code to Goldmark: 

`<img\s+src="(?<src>[^"]+)"(?:[^>]+alt="(?<alt>[^"]+)")?[^>]*>`

to 

`!\[${alt}\](${src})`

note that some adjustments might be needed after to account for incorrect image paths and lack of alt text

**Comment by tcatapano** [comment]
Note also, the Goldmark syntax will not allow for sizing images. For this, use the `figure` shortcodes see issue

**Comment by njr2128** [comment]
UPDATE: we no longer want to use the shortcodes! Use markdown or html syntax.

This needs to be checked across all pages and updated to one of those syntaxes if not already in that syntax

**Comment by ps2270** [comment]
done. closing.
