### ISSUE TITLE
change static resources to match new syntax and filepaths

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/research-teaching-companion#64]
Any static resources (pdfs, pptxs, docx, etc) that are included in any .md page in /content/ are included as if they are in the Sandbox. We need to update the syntax and the filepaths

**Comment by njr2128** [comment]
Origin syntax includes:
- `[Presentation: Preparing and Painting Blue Pigment in the Renaissance](fa22_skillbuilding-azurite-presentation-full.pdf)`
- `[<u>spreadsheet</u>](../data/fa21_jacobson_beah_final-project-know_tl_know.xlsx)`

**Comment by njr2128** [comment]
Target syntax: 
- [Stucco for Molding Assignment Sheet]({{<ref "activity_sp22_azurite-preparation" >}})

**Comment by tcatapano** [comment]
here are links that a reported not working by hugo:

uchacz_2024_lab2_reflection-assignment.docx" AT: "resources/activity-sheets/activitysheet_paintingpigments.md:23:49"
uchacz_2024_lab2_reflection-assignment.pdf" AT: "resources/activity-sheets/activitysheet_paintingpigments.md:23:113"
presentation_sp23_rosenkranz_naomi_lakes_cochineal-history-chem-prep" AT: "resources/activity-sheets/activitysheet_lake-pigments.md:96:71"
presentation_sp23_rosenkranz_naomi_lakes_madder-history-chem-prep" AT: "resources/activity-sheets/activitysheet_lake-pigments.md:97:68"
uchacz_2024_lab1_reflection-assignment-background.docx" AT: "resources/activity-sheets/activitysheet_lake-pigments.md:99:51"
uchacz_2024_lab1_reflection-assignment-background.pdf" AT: "resources/activity-sheets/activitysheet_lake-pigments.md:99:126"
uchacz_2024_lab1_reflection-assignment.docx" AT: "resources/activity-sheets/activitysheet_lake-pigments.md:100:71"
uchacz_2024_lab1_reflection-assignment.pdf" AT: "resources/activity-sheets/activitysheet_lake-pigments.md:100:135"
lakes-in-Fr-640_2021.pdf" AT: "resources/activity-sheets/activitysheet_lake-pigments.md:120:59"
documents/activity-sheets/lakes-trade-labor-in-Fr640.pdf" AT: "resources/activity-sheets/activitysheet_lake-pigments.md:121:64"
sp23_gorup_sophie_final-project_women-at-work.pdf" AT: "resources/student-projects/_index.md:72:31"
sp23_gorup_sophie_final-project_women-at-work.pdf" AT: "resources/student-projects/_index.md:72:119"
sp23_gorup_sophie_final-project_women-at-work.pptx" AT: "resources/student-projects/_index.md:72:194"
materials" AT: "resources/student-projects/_index.md:83:61"
/documents/student-projects/fa21_jacobson_beah_final-project-know_tl_know.pdf" AT: "resources/student-projects/fa21_jacobson_beah_final-project-know.md:63:22"
/documents/student-projects/fa21_ghoneima_hana_final-project_tl_say.pdf" AT: "resources/student-projects/fa21_ghoneima_hana_final-project-oral-culture.md:91:119"
/documents/student-projects/fa21_ghoneima_hana_final-project_tl_said.pdf" AT: "resources/student-projects/fa21_ghoneima_hana_final-project-oral-culture.md:95:120"
/documents/student-projects/fa21_ghoneima_hana_final-project_tl_pro.pdf" AT: "resources/student-projects/fa21_ghoneima_hana_final-project-oral-culture.md:186:117"
/documents/student-projects/fa21_ghoneima_hana_final-project_tl_pl.pdf" AT: "resources/student-projects/fa21_ghoneima_hana_final-project-oral-culture.md:192:117"
/documents/student-projects/su21_branscum_final-project_recipe-data.pdf" AT: "resources/student-projects/su21_branscum_elizabeth_final-project-medicinal.md:75:108"
/documents/student-projects/su22_fld_cunningham_annika_onion-skin-dyeing-template+notes.pdf" AT: "resources/student-projects/su22_fld_cunningham_annika_onion-skin-dyeing.md:32:53"
/documents/student-projects/su22_fld_cunningham_annika_onion-skin-dyeing-template+notes-2-greens.pdf" AT: "resources/student-projects/su22_fld_cunningham_annika_onion-skin-dyeing.md:33:52"

**Comment by ps2270** [comment]
superseded. closing
