### ISSUE TITLE
Web Page - revise home page and Resources web page title so they match

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#65]
Need to change all to
Making and Knowing
rather than M&K or Making & Knowing

**Comment by ps2270** [comment]
Rethinking the titles for the Resources:

Making & Knowing Syllabi
M&K Resources in Use
Reflections on Hands-On
Lesson Plans for Hands-On
Student Projects
Digital Making and Knowing

If these are ok with you, @njr2128 and @tcatapano and @thuchacz , we can rename buttons on Home Page and Resources Web Page.

**Comment by njr2128** [comment]
done
