### ISSUE TITLE
create lake pigment page

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/research-teaching-companion#67]
And populate with content that is already part of the "activity sheet" from the Sandbox, but also include additional resources

**Comment by njr2128** [comment]
text to copy 
“Paduan Manuscript,” (anonymous, Venice, late 16th-17th century) 
Mary P. Merrifield, Medieval and Renaissance Treatises on the Arts of Painting: Original Texts with English Translations (1849, Dover Publications, 1969), p. 702.

**Comment by ps2270** [comment]
Update as of 4.28.24: NJR & THU completed this with a some language that needs to be fixed.
NJR & THU will continue to work on this.

**Comment by ps2270** [comment]
@njr2128 
the following instruction sheets need to be uploaded to static and linked on this page: https://github.com/cu-mkp/research-teaching-companion/edit/main/content/resources/activity-sheets/activitysheet_lake-pigments.md

Lake-Making in the Classroom: Recipe Handouts
    Cochineal Standard
    Cochineal Reversed
    Madder (+ historical recipes)
    Weld (needs checking — double recipe)
    Logwood (needs fixing — double recipe)
    Sappanwood (needs handout made)
    Buckthorn (needs handout made)

**Comment by thuchacz** [comment]
I have double checked the recipes, updated the protocol sheets, and consistified the formatting across the following, which are now all linked as both DOCX and PDF on the lakes page:
- cochineal (standard)
- cochineal (reversed)
- madder (standard)
- weld (standard)
- logwood (standard)

I have never made pigments from sappanwood or buckthorn, so I don't have experience to inform the making of an activity sheet. I have deleted the following placeholders from the lakes page in RTC:
- Sappanwood (needs handout made)
- Buckthorn (needs handout made)

If you end up making these, you'll know where to add them.

**Comment by ps2270** [comment]
@thuchacz @njr2128 
I think this line is unfinished in this page:
"Pigment cards / pics"
Can you correct, complete, and/or delete, please?

**Comment by thuchacz** [comment]
Added paint sample card image to both the making lakes and making paint pages.

**Comment by thuchacz** [comment]
@ps2270 If there's nothing more to add/change, this issue can probably be closed.

**Comment by ps2270** [comment]
@thuchacz Thank you! Closing as completed.
