### ISSUE TITLE
create dyeing page

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/research-teaching-companion#70]
New webpage to contextualize assignments around dyeing with natural colorants.

**Comment by ps2270** [comment]
THU and NJR completed DYEING

**Comment by ps2270** [comment]
@thuchacz and @njr2128 The links to activity sheets on this page don't seem to link to the correct items. Please review!

**Comment by ps2270** [comment]
@thuchacz and @njr2128 : I think I figured out the problems with links to content and I have revised. I found this activity sheet:
[Dyeing with Natural Colors: Resources and Activity Sheets](/resources/activity-sheets/dyes-assignment)
which was unused and I added it under the "Activity Sheets and Assignments" heading.  Please change if that is not correct.

**Comment by thuchacz** [comment]
I'm not sure what that .md page is. I think @njr2128 must have made it, but I suspect it pre-dates our April work-sprint. The link out to NJR's google photos of the dyeing sample books is something we don't have otherwise, but it's an open question whether we should be linking out to Naomi's personal google photo albums. The other links on the .md page are all broken, but I can see that some are accounted for elsewhere on the dyeing page under different titles (though they link out to the same PDFs, some of which are now in different places in the repository). I'd have to look more carefully, but I don't think this .md page is a resource we meant to include.
@njr2128, what do you think?

**Comment by ps2270** [comment]
Ok, that's fine and sort of what I thought might be the case. I'll
wait for @Naomi
Rosenkranz ***@***.***> , then delete it from the index page
again if so.

**Comment by ps2270** [comment]
resolved. closing
