### ISSUE TITLE
Tables in Web pages and Contents

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#73]
Web page Table in About -> credits
https://cu-mkp.github.io/research-teaching-companion/credits/

Example student essay:
https://cu-mkp.github.io/research-teaching-companion/resources/student-projects/fa21_ghoneima_hana_final-project-oral-culture/
See appendix

**Comment by ps2270** [comment]
Terry and Pamela went through Student Essay tables and they do not seem to be a problem. 
Credits page maybe should be migrated from Edition as something stand-alone.

**Comment by tcatapano** [comment]
some files might have both markdown and html tables and the html does not get processed/display. see: https://github.com/cu-mkp/research-teaching-companion/blob/main/content/resources/student-projects/fa21_lin%2Bsundar_danli%2Banusha_final-project_regimens-remedies.md

**Comment by njr2128** [comment]
Terry has now allowed for html passthrough #76
