### ISSUE TITLE
update breadmolding assignment

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/research-teaching-companion#8]
Organize and add/remove resources.

Work first in a copy of the assignment in GD, then transform to `.md` and upload both here and to the Sandbox version (https://github.com/cu-mkp/sandbox/blob/main/docs/breadmolding-assignment.md)

**Comment by ps2270** [comment]
Breadmolding is finished, pending read over by NJR if necessary.
Thanks to Tillmann and Sophie

**Comment by ps2270** [comment]
breadmolding is complete. closing
