### ISSUE TITLE
create historical culinary reconstruction activity-sheet

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/research-teaching-companion#82]
Work from the most recent M&K HIST GR4962: https://docs.google.com/document/d/1UvcR_0ClX_7lefNUdWeJ-H1OW7_jvIqwL_wvN8j6vE4/edit

Check also the syllabus for the weeks surrounding HCR: https://docs.google.com/document/d/1G4YveE4xRk2tv9NDa7tbXlhkunTbtXLIiwt7m_HNeXM/edit

**Comment by njr2128** [comment]
Duplicate of #27! Apologies. Here is that content from @ps2270:
[2023 version](https://docs.google.com/document/d/1UvcR_0ClX_7lefNUdWeJ-H1OW7_jvIqwL_wvN8j6vE4/edit)

- Use Template to format
- are links necessary and durable 
- how to deal with the assigning of obscure recipes? Include these as pdfs attached to the Instructor sheet?

**Comment by SJPitman** [comment]
@njr2128 
Please can you make markdown versions of the three files in this folder: https://docs.google.com/document/d/1HfiDWKzG2s9QyxnkuifGniCqQyXctVWmhbgXOzgsDjU/edit?usp=drive_link

**Comment by ps2270** [comment]
PHS Review thoughts:
- Take out reference to Clio in Student worksheet

In Guide to Historical Recipe Collections
- In addition to entire texts, which in our experience often baffle the students, provide a few pdfs of recipes: from here: https://drive.google.com/drive/u/1/folders/0B25oBcRXnBbJem9Od1c1QTZ1V3M?resourcekey=0-HAx0VFAnB9kFHCjIIeqEiQ
- Labeled as Sample Recipes and then mention these on the Instructor Sheet

Instructor Sheet:
- FOR M&K Team LATER: Add a link to a syllabus in which the activity appears, e.g., sp23 (and, in the syllabus, link out to the lesson plan)
- Add PDF and DOCX

Instructor Sheet
-  We have provided a few sufficiently obscure pdfs of recipes as examples
- Additional material under "Additional readings for more advanced students" - when considering authenticity of reconstruction, create a document for the students in which they are required to record one thought about reconstruction ,e.g., https://docs.google.com/document/d/1vkDGKMq3da9HR44aA2KytQC74QTNaDyIzVflA-FemTs/edit
- From these thoughts, you may want to have the students collectively create a "Reconstruction Template" https://docs.google.com/document/d/1HPf2VDAjAS9rOU9B6v35mOb1sQe_ugcVj8xjku3SqCA/edit#heading=h.8kblem9mwcg5

possible instructions:
Monday, Jan 30: Upload your presentation (Powerpoint, etc.) of your HCR to Courseworks 
Each group member should upload the same presentation in Courseworks
Your presentation on Jan 31 must be 10 minutes max.
Practice delivering the presentation as we must keep to time in class.
You are responsible for sourcing and purchasing your own materials. If this presents any hardship for you, please speak to us about it before you buy anything. We may be able to reimburse you for -- or purchase for you -- some of the materials. 
IN CLASS 
10:10–11:40	Presentations of HCR process and results 
11:40–12pm	Commentary on the results (and consumption, if possible and safe to do)
		
Due the next week: Reconstruction Thoughts - Add at least one comment/thought to the document.

**Comment by ps2270** [comment]
HCR is ready, pending review by NJR if necessary. Thanks to Sophie and Tillmann

**Comment by ps2270** [comment]
Only remaining item is to add the link to the syllabus once it is available on the webpage: https://cu-mkp.github.io/research-teaching-companion/resources/activity-sheets/activitysheet_hcr-instructor/

**Comment by ps2270** [comment]
HCR activity sheet complete
