### ISSUE TITLE
Macomber essay broken links

### ISSUE THREAD

**Issue by LydiaDef** [cu-mkp/research-teaching-companion#84]
#58 

Line 64

```
_See [su21_macomber_figures.R](../code/su21_macomber_figures.R) for sourcecode of this chart._
```

https://github.com/cu-mkp/research-teaching-companion/blob/2b1d1a1c65efa30c8b6290526f6fa2b357a528e6/content/resources/student-projects/su21_macomber_sophie_final-project-figures.md?plain=1#L64C1-L64C95

**Comment by ps2270** [comment]
fixed. closing
