### ISSUE TITLE
Christensen images not working - multiple throughout essay 

### ISSUE THREAD

**Issue by LydiaDef** [cu-mkp/research-teaching-companion#85]
#58 

```
<th><p>![IMAGE](/images/media-christensen/image5.png)</p>
```

https://github.com/cu-mkp/research-teaching-companion/blob/2783311db0ec7194d6814f1995794f31ebc8b4e1/content/resources/student-projects/su21_christensen_anna_final-project-natural-things.md?plain=1#L59

**Comment by ps2270** [comment]
Lydia and Pamela tried to fix Fig. 1 by deleting the html around the md link to the image, but it did not fix the problem

**Comment by ps2270** [comment]
fixed by correcting syntax to md.
closing now
