### ISSUE TITLE
Ghoneima spreadsheet not working 

### ISSUE THREAD

**Issue by LydiaDef** [cu-mkp/research-teaching-companion#87]
#59 

Spreadsheet link isn't working - line 91

```
-   For a look at all collected data involving the word “say,” please refer to the following [<u>spreadsheet</u>]({{< ref "/documents/student-projects/fa21_ghoneima_hana_final-project_tl_say.pdf" >}}).
```

https://github.com/cu-mkp/research-teaching-companion/blob/6c3630839cf47bbed2db5ac3832cc1a809b70d7d/content/resources/student-projects/fa21_ghoneima_hana_final-project-oral-culture.md?plain=1#L91

**Comment by LydiaDef** [comment]
I tried to change this to markdown, but I can't tell if it actually went through - it doesn't look like it changed in the code, and I'm getting a "You must be on a branch to make or propose changes to this file." message when I try to edit.

**Comment by ps2270** [comment]
#44 
fixed. closing.
