### ISSUE TITLE
Ghoneima spreadsheet not working 

### ISSUE THREAD

**Issue by LydiaDef** [cu-mkp/research-teaching-companion#88]
#59 

Spreadsheet link isn't working - line 95

```
-   For a look at all collected data involving the word “said,” please refer to the following [<u>spreadsheet</u>]({{< ref "/documents/student-projects/fa21_ghoneima_hana_final-project_tl_said.pdf" >}}).
```

https://github.com/cu-mkp/research-teaching-companion/blob/6c3630839cf47bbed2db5ac3832cc1a809b70d7d/content/resources/student-projects/fa21_ghoneima_hana_final-project-oral-culture.md?plain=1#L95

**Comment by ps2270** [comment]
#44 
fixed. closing
