### ISSUE TITLE
Jacobson spreadsheet link not working 

### ISSUE THREAD

**Issue by LydiaDef** [cu-mkp/research-teaching-companion#89]
#59 

Link to spreadsheet in line 63 not working 

```
[<u>spreadsheet</u>]({{< ref "/documents/student-projects/fa21_jacobson_beah_final-project-know_tl_know.pdf" >}})
```

https://github.com/cu-mkp/research-teaching-companion/blob/6c3630839cf47bbed2db5ac3832cc1a809b70d7d/content/resources/student-projects/fa21_jacobson_beah_final-project-know.md?plain=1#L63

**Comment by ps2270** [comment]
fixed
closing
