### ISSUE TITLE
commission videos from collaborators

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/research-teaching-companion#9]
Brief that PHS sent to collaborators:
> You have all done pilot classes that incorporated M&K activities, and we'd love to include in the RTC short videos from you that record your thoughts about hands-on work in the classroom.
Some of you--Sofia, Monique, Tianna--have given talks at RSA and HSS meetings that would be perfect for this purpose, so if you could record yourselves (by zoom?) giving those talks, they would be a wonderful addition to the RTC!
Or, if you preferred, the video could just include you talking about the experience of doing hands-on activities -- the merits, challenges, pitfalls, whatever!
I hope you might be able to find time to do this and that it doesn't seem too onerous -  I know how busy you all are!
We imagine that these videos would include the following (among whatever else you would want to include):
Who you are (and what did you teach)?
What hands-on activities did you do? Any from the Edition?
Challenges?
How did students react?
What difference did doing hands-on activities make to the course, the educational experience (from your perspective and your students' perspectives)?
If possible, it would be wonderful if you could include in your video (by powerpoint presentation or whatever) some photos of the class, the students (if you have permission from the students to record their faces), and the students' work.
These videos would be published (likely on the landing page of the RTC)

**Asked:**
- [x] Christina Neilson -- will do as a conversation with students
- [x] Sofia Gans -- version based on presentation for RSA digital 2022
- [x] Monique O'Connell -- will start in April
- [ ] Vera Keller -- will work with students
- [x] Tianna Uchacz -- ways she has adapted for her VIZ students

**Comment by ps2270** [comment]
As of 5.2.24:
Vera Keller is the one outstanding video-maker (she said she'd get it to us in May)
Tianna's information is already in the Resources in Use Page
Christina and Sophie's videos should be available on the Resources in Use Page [and perhaps the Reflections page]

**Comment by ps2270** [comment]
Vera Keller will get the video to us around Aug. 1. the others are complete and on the site.

**Comment by ps2270** [comment]
#43 contains info re Vera Keller. Closing this now.
