### ISSUE TITLE
Yang/Wei PDF not loading

### ISSUE THREAD

**Issue by LydiaDef** [cu-mkp/research-teaching-companion#92]
#60 

PDF not loading - Line 10

```
[A Visual Presentation of the Pop-up Book \[PDF\]](sp22_wei+yang_jianing+luxi_popup-presentation.pdf)
```

https://github.com/cu-mkp/research-teaching-companion/blob/6f270aa26cee36854e914c3ee164f071f0422255/content/resources/student-projects/sp22_wei%2Byang_jianing%2Bluxi_popup.md?plain=1#L10

**Comment by ps2270** [comment]
Works now
