### ISSUE TITLE
Shi essay images not loading

### ISSUE THREAD

**Issue by LydiaDef** [cu-mkp/research-teaching-companion#95]
#61 

Line 21 - image not loading 

```
![Figure 1/images/images/media-shi/image1.png) ![Figure 2](images/images/media-shi/image2.png) 
```

https://github.com/cu-mkp/research-teaching-companion/blob/bd33057ced0c9a488a12fc21b3323d6661cc5719/content/resources/student-projects/sp23_shi-jingxian_final-project_paintbrushes.md?plain=1#L21

**Comment by ps2270** [comment]
Changed the figures from .md to .html curly brackets and that solved the problem
