### ISSUE TITLE
create kitchen pigment resource

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/research-teaching-companion#98]
based n the dyeing at home in your kitchen resources: 
- https://github.com/cu-mkp/research-teaching-companion/blob/main/static/documents/activity-sheets/activitysheet_dye-kitchen-dyeing.docx
- https://github.com/cu-mkp/research-teaching-companion/blob/main/static/documents/activity-sheets/activitysheet_dye-kitchen-dyeing.pdf

**Comment by ps2270** [comment]
this seems to be complete. closing
